# Generated by Django 4.2.5 on 2023-11-29 16:08

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("store_app", "0003_tag_images"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="description",
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="information",
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="unique_id",
            field=models.CharField(blank=True, max_length=200, null=True, unique=True),
        ),
    ]
